version: '3.8'

services:
  beat:
    build:
      context: .
      dockerfile: docker/Dockerfile.beat
    volumes:
      - .:/app

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    volumes:
      - .:/app
    depends_on:
      - beat
