mutation createCredential($input: input!) @api(name: ai) {
  createCredential(input: $input)
    @rest(type: "Credential", path: "/credential", method: "POST", bodyKey: "input", endpoint: "ai") {
    success
    message
  }
}
