mutation deleteCredential($credential_id: credential_id!) @api(name: ai) {
  deleteCredential(credential_id: $credential_id)
    @rest(
      type: "Credential"
      path: "/credential/{args.credential_id}"
      method: "DELETE"
      bodyKey: "input"
      endpoint: "ai"
    ) {
    success
    message
  }
}
