query getCredentials @api(name: "ai") {
  getCredentials @rest(type: "Credential", path: "/credential", method: "GET", endpoint: "ai") {
    id
    credential_name
    account_id
    created_by
    created_on
  }
}
