mutation update_credential($credential_id: credential_id!, $input: input!) @api(name: ai) {
  update_credential(credential_id: $credential_id, input: $input)
    @rest(
        type: "Credential", 
        path: "/credential/{args.credential_id}", 
        method: "PUT", 
        bodyKey: "input", 
        endpoint: "ai"
    ) {
    success
    message
  }
}
