mutation createSecret($input: input!) @api(name: ai) {
  createSecret(input: $input)
    @rest(type: "CreateSecret", path: "/secret", method: "POST", bodyKey: "input", endpoint: "ai") {
    success
    message
  }
}
