mutation deleteSecret($secret_id: secret_id!) @api(name: ai) {
  deleteSecret(secret_id: $secret_id)
    @rest(
      type: "Secret"
      path: "/secret/{args.secret_id}"
      method: "DELETE"
      bodyKey: "input"
      endpoint: "ai"
    ) {
    success
    message
  }
}
