query secretById @api(name: "ai") {
  secretById @rest(type: "Secret", path: "/secret", method: "GET", endpoint: "ai") {
    id
    secret_name
    secret_description
    last_retrieved_on
    account_id
    created_by
    created_on
  }
}
