query secretById($secret_id: secret_id!) @api(name: "ai") {
  secretById(secret_id: $secret_id) 
    @rest(
      type: "Secret", 
      path: "/secret/{args.secret_id}",
      method: "GET", 
      endpoint: "ai"
    ) {
      id
      secret_name
      secret_description
      last_retrieved_on
      account_id
      created_by
      created_on
  }
}
