"""Update Credential field

Revision ID: 48ec1da703b9
Revises: 9d2011200d93
Create Date: 2024-06-14 18:23:41.396051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48ec1da703b9'
down_revision: Union[str, None] = '9d2011200d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credential', sa.Column('credential_name', sa.String(), nullable=False))
    op.drop_column('credential', 'secret_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credential', sa.Column('secret_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('credential', 'credential_name')
    # ### end Alembic commands ###
