"""Update secret model

Revision ID: 62e117fc3e6f
Revises: add36382624a
Create Date: 2024-06-13 13:23:10.539571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62e117fc3e6f'
down_revision: Union[str, None] = 'add36382624a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secret', sa.Column('last_retrieved_on', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('secret', 'last_retrieved_At')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secret', sa.Column('last_retrieved_At', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('secret', 'last_retrieved_on')
    # ### end Alembic commands ###
