"""Add credential column on template table

Revision ID: 7bd53426edbc
Revises: 48ec1da703b9
Create Date: 2024-06-14 19:45:36.512973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bd53426edbc'
down_revision: Union[str, None] = '48ec1da703b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column('credential', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'template', 'credential', ['credential'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'template', type_='foreignkey')
    op.drop_column('template', 'credential')
    # ### end Alembic commands ###
