"""Add credential model

Revision ID: 9d2011200d93
Revises: 62e117fc3e6f
Create Date: 2024-06-13 19:38:16.025377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2011200d93'
down_revision: Union[str, None] = '62e117fc3e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credential',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('secret_name', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='fk_created_by', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modified_by'], ['user.id'], name='fk_modified_by', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credential_created_by'), 'credential', ['created_by'], unique=False)
    op.create_index(op.f('ix_credential_is_deleted'), 'credential', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_credential_modified_by'), 'credential', ['modified_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credential_modified_by'), table_name='credential')
    op.drop_index(op.f('ix_credential_is_deleted'), table_name='credential')
    op.drop_index(op.f('ix_credential_created_by'), table_name='credential')
    op.drop_table('credential')
    # ### end Alembic commands ###
