"""Add secret model

Revision ID: add36382624a
Revises: 8ee8b2ab331f
Create Date: 2024-06-13 13:20:50.103188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add36382624a'
down_revision: Union[str, None] = '8ee8b2ab331f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('secret_description', sa.String(), nullable=True),
    sa.Column('secret_name', sa.String(), nullable=False),
    sa.Column('secret_value', sa.String(), nullable=False),
    sa.Column('last_retrieved_At', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='fk_created_by', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modified_by'], ['user.id'], name='fk_modified_by', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secret_created_by'), 'secret', ['created_by'], unique=False)
    op.create_index(op.f('ix_secret_is_deleted'), 'secret', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_secret_modified_by'), 'secret', ['modified_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_secret_modified_by'), table_name='secret')
    op.drop_index(op.f('ix_secret_is_deleted'), table_name='secret')
    op.drop_index(op.f('ix_secret_created_by'), table_name='secret')
    op.drop_table('secret')
    # ### end Alembic commands ###
