name: Deploy React App

on:
  push:
    branches:
      - main
      - feature/deployment-cd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: apps/ui/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('apps/ui/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: yarn install
      working-directory: apps/ui

    - name: Build the React app
      run: yarn build
      working-directory: apps/ui

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to S3
      run: aws s3 sync apps/ui/build s3://datura-subnets --delete

    - name: Invalidate CloudFront cache
      run: aws cloudfront create-invalidation --distribution-id EWZLE65DSGHC2 --paths "/*"
