name: EB deploy api

on:
  push:
    branches:
      - main
      - feature/deployment-cd

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install EB CLI using pip
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          cd apps/server
          docker buildx build --platform linux/amd64,linux/arm64 -t theiskaa/datura-subnets-api:latest . --push

      - name: Init EB CLI for API
        run: |
          eb init -p docker DaturaSubnetsAPI --region ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy API to Elastic Beanstalk
        run: |
          eb deploy DaturaSubnetsAPI-env
